In [1]:
import numpy as np

# the basics

In [2]:
a = np.array([1 , 2 , 3] , dtype = "int16")
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#get dimension

print(a.ndim)
print(b.ndim)

1
2


In [5]:
# get shape

print(a.shape)
print(b.shape)

(3,)
(3, 3)


In [6]:
# get type
print(a.dtype) # by default it is "int32"
print(b.dtype)

int16
int32


In [7]:
# get size

print(a.size)
print(b.size)

# get memory size

print( "memory : " , a.itemsize)
print(b.itemsize)

3
9
memory :  2
4


In [8]:
# get total size

print(a.nbytes)
print(b.nbytes)

6
36


# Accessing / changing specific elements, rows , columns , etc.

In [9]:
c = np.array([[1,2,3,4,5,6,7],[9,8,7,6,5,4,3]])
print(c)

[[1 2 3 4 5 6 7]
 [9 8 7 6 5 4 3]]


In [10]:
c.shape

(2, 7)

In [11]:
# get a specific element [r , c]
c[1 , 5]


4

In [12]:
# get a specific row

c[0 , :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# get a specific column
c[: , 2]

array([3, 7])

In [14]:
# getting a little more fancy [start : end : step]

c[0,1:6:2]

array([2, 4, 6])

In [15]:
c[1,5] = 20

In [16]:
print(c)

[[ 1  2  3  4  5  6  7]
 [ 9  8  7  6  5 20  3]]


In [17]:
c[: , 2] = [10 ,30]
print(c)

[[ 1  2 10  4  5  6  7]
 [ 9  8 30  6  5 20  3]]


###  3-d example

In [18]:
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
d[0,1,1]

5

In [20]:
d[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [21]:
d[:,1,:] = [[9,9,9] , [8,8,8]]

In [22]:
print(d)

[[[1 2 3]
  [9 9 9]]

 [[7 8 9]
  [8 8 8]]]


#  Initializing Different Types of Arrays

In [23]:
# all 0s matrix

np.zeros((2,3)  , dtype = "int16")

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [24]:
np.ones((4,4,2), dtype = "int32")

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [25]:
# any other number
np.full((2,2) , 99)

array([[99, 99],
       [99, 99]])

In [26]:
# any other number(full_like)

np.full_like(b,4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [27]:
# random decimal numbers

print(np.random.rand(4,2))
print("-----------------")

print(np.random.sample(b.shape))

[[0.5802291  0.74910777]
 [0.83890992 0.88641688]
 [0.32946067 0.32342263]
 [0.82792762 0.86307222]]
-----------------
[[0.70571576 0.80901381 0.15578609]
 [0.97081641 0.81518649 0.69073771]
 [0.01277197 0.37263306 0.51590038]]


In [28]:
# random integer values

print(np.random.randint(4,12 , size = (3,3)))

[[ 8  5 11]
 [ 9 11  5]
 [ 4  8  4]]


In [31]:
# identity matrix

np.identity(5 , dtype = "int8")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [35]:
# repeating an array
a= np.array([[1,2,3]])

arr = np.repeat(a , 3 , axis = 0)
print(arr)
arr1 = np.repeat(a , 3 , axis = 1)
print(arr1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [ ]:
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

op = np.ones((5,5) , dtype = "int32" )

print(op)
print("--------------------------------")

z = np.zeros((3,3), dtype = "int32")

z[1,1] = 9
print(z)
print("--------------------------------")
op[1:4 , 1:4] = z
print(op)

### Be careful when copying arrays !!!

In [40]:
a = np.array([1,2,3])
b=a
c = a.copy()
c[1] = 99
b[0] = 100
print(a)

[100   2   3]


### Mathematics

In [41]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [42]:
print(a+2)

[3 4 5 6]


In [43]:
print(a-2)

[-1  0  1  2]


In [44]:
print(a*2)

[2 4 6 8]


In [45]:
print(a/2)

[0.5 1.  1.5 2. ]


In [46]:
print(a**2)

[ 1  4  9 16]


In [51]:
b= np.array([50,60,70,90])
print(a+b)

[51 62 73 94]


In [52]:
# take the sin 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [54]:
print(np.cos(b))

[ 0.96496603 -0.95241298  0.6333192  -0.44807362]


### Linear Algebra

In [58]:
a = np.ones((2,3) , dtype = "int32")
print(a)
print("------------------------")
b = np.full((3,2) , 2)
print(b)
print("------------------------")
print(np.matmul(a,b))

[[1 1 1]
 [1 1 1]]
------------------------
[[2 2]
 [2 2]
 [2 2]]
------------------------
[[6 6]
 [6 6]]


In [59]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

In [61]:
print(np.linalg.det(op))

0.0


### Statistics

In [63]:
stats = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(stats)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
np.min(stats)

1

In [65]:
np.max(stats)

9

In [68]:
np.min(stats ,axis = 1 )

array([1, 4, 7])

In [70]:
np.sum(stats , axis =0)

array([12, 15, 18])

### Reorganizing Arrays

In [75]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [80]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2= np.array([5,6,7,8])

print(np.vstack([v1,v2,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [81]:
print(np.hstack([v1,v1,v2, v2]))

[1 2 3 4 1 2 3 4 5 6 7 8 5 6 7 8]
